### ISSUE TITLE
Positive signing tests fail

### ISSUE THREAD

**Issue by mkl-public** [methics/laverca-csc-client#2]
Currently all `TestSignHash` tests except the negative test `testSCAL2InvalidHash` fail.

There appears to be an issue in the test PKI.

**Comment by Hemuu** [comment]
Thanks for pointing this out. It was indeed an issue in the backend service that the tests rely on.

Should be fixed now.

**Comment by mkl-public** [comment]
Yes, all works fine again. Thanks!
