### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by mkl-public** [methics/laverca-csc-client#4]
The laverca csc client depends on old third party libraries. In particular it depends on okhttp 2.7.5 which is some 8 years old. The current stable release appears to be 4.12.0 and there already are a number of 5.0.0-ALPHA releases.

Are there any plans to update the csc client to more current dependencies? Or are there any good reasons not to do so?

**Comment by Hemuu** [comment]
> Are there any plans to update the csc client to more current dependencies? Or are there any good reasons not to do so?

No particular reason to not upgrade. Thanks for pointing this out. Will look into it - and possibly setup dependabot to warn about obsolete libraries.

**Comment by mkl-public** [comment]
Great that you updated the dependencies. I'll update to the new version.
